// <auto-generated />
using System;
using LCAP.HRMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LCAP.HRMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907095757_DepartmentMaster")]
    partial class DepartmentMaster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LCAP.HRMS.Domain.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("India");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsHeadOffice")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "BranchCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Branches_CompanyId_BranchCode");

                    b.ToTable("Branches", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Branches_BranchCode", "LTRIM(RTRIM([BranchCode])) <> ''");

                            t.HasCheckConstraint("CK_Branches_BranchName", "LTRIM(RTRIM([BranchName])) <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3e36a15-4efb-441e-bbd8-f6cf916f6107"),
                            BranchCode = "PATNA-HO",
                            BranchName = "Patna Head Office",
                            City = "Patna",
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            Country = "India",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            IsActive = true,
                            IsDeleted = false,
                            IsHeadOffice = true,
                            State = "Bihar"
                        });
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("India");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ESIRegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GSTIN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LegalName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PAN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PFRegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PayrollCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("INR");

                    b.Property<int>("PayrollDay")
                        .HasColumnType("int");

                    b.Property<string>("PinCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RegisteredAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SalaryPaymentDay")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TAN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Companies_CompanyCode");

                    b.ToTable("Companies", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Companies_CompanyCode", "LTRIM(RTRIM([CompanyCode])) <> ''");

                            t.HasCheckConstraint("CK_Companies_CompanyName", "LTRIM(RTRIM([CompanyName])) <> ''");

                            t.HasCheckConstraint("CK_Companies_PayrollDay", "[PayrollDay] BETWEEN 1 AND 31");

                            t.HasCheckConstraint("CK_Companies_SalaryPaymentDay", "[SalaryPaymentDay] BETWEEN 1 AND 31");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CompanyCode = "LCAP",
                            CompanyName = "LCAP",
                            Country = "India",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            IsActive = true,
                            IsDeleted = false,
                            PayrollCurrency = "INR",
                            PayrollDay = 1,
                            SalaryPaymentDay = 1,
                            State = "Bihar"
                        });
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Departments.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentDepartmentId");

                    b.HasIndex("CompanyId", "DepartmentCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Departments_CompanyId_DepartmentCode");

                    b.HasIndex("CompanyId", "ParentDepartmentId");

                    b.ToTable("Departments", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Departments_DepartmentCode", "LTRIM(RTRIM([DepartmentCode])) <> ''");

                            t.HasCheckConstraint("CK_Departments_DepartmentName", "LTRIM(RTRIM([DepartmentName])) <> ''");

                            t.HasCheckConstraint("CK_Departments_NotOwnParent", "[ParentDepartmentId] IS NULL OR [ParentDepartmentId] <> [Id]");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ebde002-3e2e-4ac4-bcca-7a0ea3bd4201"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DepartmentCode = "HR",
                            DepartmentName = "Human Resources",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("0ebde002-3e2e-4ac4-bcca-7a0ea3bd4202"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DepartmentCode = "FIN",
                            DepartmentName = "Finance",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("0ebde002-3e2e-4ac4-bcca-7a0ea3bd4203"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DepartmentCode = "SALES",
                            DepartmentName = "Sales",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("0ebde002-3e2e-4ac4-bcca-7a0ea3bd4204"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DepartmentCode = "OPS",
                            DepartmentName = "Operations",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("0ebde002-3e2e-4ac4-bcca-7a0ea3bd4205"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DepartmentCode = "MGMT",
                            DepartmentName = "Management",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Branches.Branch", b =>
                {
                    b.HasOne("LCAP.HRMS.Domain.Companies.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Departments.Department", b =>
                {
                    b.HasOne("LCAP.HRMS.Domain.Companies.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCAP.HRMS.Domain.Departments.Department", "ParentDepartment")
                        .WithMany("Children")
                        .HasForeignKey("CompanyId", "ParentDepartmentId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Companies.Company", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Departments.Department", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
