// <auto-generated />
using System;
using LCAP.HRMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LCAP.HRMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907162713_GeoAttendance")]
    partial class GeoAttendance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LCAP.HRMS.Domain.Attendance.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("CheckInAccuracyMeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<decimal?>("CheckInDistanceMeters")
                        .HasPrecision(14, 3)
                        .HasColumnType("decimal(14,3)");

                    b.Property<decimal?>("CheckInLatitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("CheckInLongitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("CheckInSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset?>("CheckInTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("CheckInWithinGeofence")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CheckOutAccuracyMeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<decimal?>("CheckOutDistanceMeters")
                        .HasPrecision(14, 3)
                        .HasColumnType("decimal(14,3)");

                    b.Property<decimal?>("CheckOutLatitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("CheckOutLongitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("CheckOutSource")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset?>("CheckOutTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("CheckOutWithinGeofence")
                        .HasColumnType("bit");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("WorkLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_AttendanceRecords_EmployeeId_Open")
                        .HasFilter("[IsDeleted] = 0 AND [CheckOutTime] IS NULL");

                    b.HasIndex("ShiftId");

                    b.HasIndex("CompanyId", "AttendanceDate");

                    b.HasIndex("EmployeeId", "AttendanceDate")
                        .IsUnique()
                        .HasDatabaseName("UX_AttendanceRecords_EmployeeId_AttendanceDate");

                    b.HasIndex("WorkLocationId", "AttendanceDate");

                    b.ToTable("AttendanceRecords", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_AttendanceRecords_CheckInAccuracy", "[CheckInAccuracyMeters] IS NULL OR [CheckInAccuracyMeters] > 0");

                            t.HasCheckConstraint("CK_AttendanceRecords_CheckInDistance", "[CheckInDistanceMeters] IS NULL OR [CheckInDistanceMeters] >= 0");

                            t.HasCheckConstraint("CK_AttendanceRecords_CheckInLatitude", "[CheckInLatitude] IS NULL OR [CheckInLatitude] BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_AttendanceRecords_CheckInLongitude", "[CheckInLongitude] IS NULL OR [CheckInLongitude] BETWEEN -180 AND 180");

                            t.HasCheckConstraint("CK_AttendanceRecords_CheckOutAccuracy", "[CheckOutAccuracyMeters] IS NULL OR [CheckOutAccuracyMeters] > 0");

                            t.HasCheckConstraint("CK_AttendanceRecords_CheckOutDistance", "[CheckOutDistanceMeters] IS NULL OR [CheckOutDistanceMeters] >= 0");

                            t.HasCheckConstraint("CK_AttendanceRecords_CheckOutLatitude", "[CheckOutLatitude] IS NULL OR [CheckOutLatitude] BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_AttendanceRecords_CheckOutLongitude", "[CheckOutLongitude] IS NULL OR [CheckOutLongitude] BETWEEN -180 AND 180");

                            t.HasCheckConstraint("CK_AttendanceRecords_Status", "([Status] = 1 AND [CheckOutTime] IS NULL) OR ([Status] = 2 AND [CheckOutTime] IS NOT NULL)");

                            t.HasCheckConstraint("CK_AttendanceRecords_Times", "[CheckInTime] IS NOT NULL AND ([CheckOutTime] IS NULL OR [CheckOutTime] >= [CheckInTime])");
                        });
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("India");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsHeadOffice")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "BranchCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Branches_CompanyId_BranchCode");

                    b.ToTable("Branches", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Branches_BranchCode", "LTRIM(RTRIM([BranchCode])) <> ''");

                            t.HasCheckConstraint("CK_Branches_BranchName", "LTRIM(RTRIM([BranchName])) <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3e36a15-4efb-441e-bbd8-f6cf916f6107"),
                            BranchCode = "PATNA-HO",
                            BranchName = "Patna Head Office",
                            City = "Patna",
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            Country = "India",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            IsActive = true,
                            IsDeleted = false,
                            IsHeadOffice = true,
                            State = "Bihar"
                        });
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("India");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ESIRegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GSTIN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LegalName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PAN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PFRegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PayrollCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("INR");

                    b.Property<int>("PayrollDay")
                        .HasColumnType("int");

                    b.Property<string>("PinCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RegisteredAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SalaryPaymentDay")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TAN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Companies_CompanyCode");

                    b.ToTable("Companies", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Companies_CompanyCode", "LTRIM(RTRIM([CompanyCode])) <> ''");

                            t.HasCheckConstraint("CK_Companies_CompanyName", "LTRIM(RTRIM([CompanyName])) <> ''");

                            t.HasCheckConstraint("CK_Companies_PayrollDay", "[PayrollDay] BETWEEN 1 AND 31");

                            t.HasCheckConstraint("CK_Companies_SalaryPaymentDay", "[SalaryPaymentDay] BETWEEN 1 AND 31");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CompanyCode = "LCAP",
                            CompanyName = "LCAP",
                            Country = "India",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            IsActive = true,
                            IsDeleted = false,
                            PayrollCurrency = "INR",
                            PayrollDay = 1,
                            SalaryPaymentDay = 1,
                            State = "Bihar"
                        });
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Departments.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentDepartmentId");

                    b.HasIndex("CompanyId", "DepartmentCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Departments_CompanyId_DepartmentCode");

                    b.HasIndex("CompanyId", "ParentDepartmentId");

                    b.ToTable("Departments", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Departments_DepartmentCode", "LTRIM(RTRIM([DepartmentCode])) <> ''");

                            t.HasCheckConstraint("CK_Departments_DepartmentName", "LTRIM(RTRIM([DepartmentName])) <> ''");

                            t.HasCheckConstraint("CK_Departments_NotOwnParent", "[ParentDepartmentId] IS NULL OR [ParentDepartmentId] <> [Id]");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ebde002-3e2e-4ac4-bcca-7a0ea3bd4201"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DepartmentCode = "HR",
                            DepartmentName = "Human Resources",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("0ebde002-3e2e-4ac4-bcca-7a0ea3bd4202"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DepartmentCode = "FIN",
                            DepartmentName = "Finance",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("0ebde002-3e2e-4ac4-bcca-7a0ea3bd4203"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DepartmentCode = "SALES",
                            DepartmentName = "Sales",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("0ebde002-3e2e-4ac4-bcca-7a0ea3bd4204"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DepartmentCode = "OPS",
                            DepartmentName = "Operations",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("0ebde002-3e2e-4ac4-bcca-7a0ea3bd4205"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DepartmentCode = "MGMT",
                            DepartmentName = "Management",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Designations.Designation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DesignationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsManagerial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "DesignationCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Designations_CompanyId_DesignationCode");

                    b.ToTable("Designations", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Designations_DesignationCode", "LTRIM(RTRIM([DesignationCode])) <> ''");

                            t.HasCheckConstraint("CK_Designations_DesignationName", "LTRIM(RTRIM([DesignationName])) <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("42d49a28-e6b8-46c7-aac1-11019a39d001"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DesignationCode = "EXEC",
                            DesignationName = "Executive",
                            IsActive = true,
                            IsDeleted = false,
                            IsManagerial = false
                        },
                        new
                        {
                            Id = new Guid("42d49a28-e6b8-46c7-aac1-11019a39d002"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DesignationCode = "SREXEC",
                            DesignationName = "Senior Executive",
                            IsActive = true,
                            IsDeleted = false,
                            IsManagerial = false
                        },
                        new
                        {
                            Id = new Guid("42d49a28-e6b8-46c7-aac1-11019a39d003"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DesignationCode = "TL",
                            DesignationName = "Team Leader",
                            IsActive = true,
                            IsDeleted = false,
                            IsManagerial = false
                        },
                        new
                        {
                            Id = new Guid("42d49a28-e6b8-46c7-aac1-11019a39d004"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DesignationCode = "MGR",
                            DesignationName = "Manager",
                            IsActive = true,
                            IsDeleted = false,
                            IsManagerial = false
                        },
                        new
                        {
                            Id = new Guid("42d49a28-e6b8-46c7-aac1-11019a39d005"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DesignationCode = "HRM",
                            DesignationName = "HR Manager",
                            IsActive = true,
                            IsDeleted = false,
                            IsManagerial = false
                        },
                        new
                        {
                            Id = new Guid("42d49a28-e6b8-46c7-aac1-11019a39d006"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            DesignationCode = "PAYADMIN",
                            DesignationName = "Payroll Admin",
                            IsActive = true,
                            IsDeleted = false,
                            IsManagerial = false
                        });
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AadhaarNumber")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("AccountHolderName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlternateMobileNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("BankName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfConfirmation")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOfJoining")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfResignation")
                        .HasColumnType("date");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DesignationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ESICNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<int>("EmployeeStatus")
                        .HasColumnType("int");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("int");

                    b.Property<string>("ExitReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IFSCCode")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("LastWorkingDate")
                        .HasColumnType("date");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OfficialEmail")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PAN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonalEmail")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly?>("ProbationEndDate")
                        .HasColumnType("date");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid?>("ReportingManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UAN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("WorkLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("EmployeeStatus");

                    b.HasIndex("ReportingManagerId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("WorkLocationId");

                    b.HasIndex("CompanyId", "EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_CompanyId_EmployeeCode");

                    b.HasIndex("CompanyId", "IsDeleted");

                    b.ToTable("Employees", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Employees_Code", "LTRIM(RTRIM([EmployeeCode])) <> ''");

                            t.HasCheckConstraint("CK_Employees_Confirmation", "[DateOfConfirmation] IS NULL OR [DateOfConfirmation] >= [DateOfJoining]");

                            t.HasCheckConstraint("CK_Employees_LastWorking", "[LastWorkingDate] IS NULL OR [LastWorkingDate] >= [DateOfJoining]");

                            t.HasCheckConstraint("CK_Employees_SelfManager", "[ReportingManagerId] IS NULL OR [ReportingManagerId] <> [Id]");
                        });
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Shifts.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(7)");

                    b.Property<int>("GracePeriodMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsNightShift")
                        .HasColumnType("bit");

                    b.Property<int?>("MinimumFullDayMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumHalfDayMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ShiftCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(7)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "ShiftCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Shifts_CompanyId_ShiftCode");

                    b.ToTable("Shifts", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Shifts_FullDay", "[MinimumFullDayMinutes] IS NULL OR [MinimumFullDayMinutes] >= 0");

                            t.HasCheckConstraint("CK_Shifts_GracePeriod", "[GracePeriodMinutes] >= 0");

                            t.HasCheckConstraint("CK_Shifts_HalfDay", "[MinimumHalfDayMinutes] IS NULL OR [MinimumHalfDayMinutes] >= 0");

                            t.HasCheckConstraint("CK_Shifts_NightShift", "[EndTime] > [StartTime] OR [IsNightShift] = 1");

                            t.HasCheckConstraint("CK_Shifts_ShiftCode", "LTRIM(RTRIM([ShiftCode])) <> ''");

                            t.HasCheckConstraint("CK_Shifts_ShiftName", "LTRIM(RTRIM([ShiftName])) <> ''");

                            t.HasCheckConstraint("CK_Shifts_ThresholdOrder", "[MinimumHalfDayMinutes] IS NULL OR [MinimumFullDayMinutes] IS NULL OR [MinimumHalfDayMinutes] <= [MinimumFullDayMinutes]");

                            t.HasCheckConstraint("CK_Shifts_Times", "[StartTime] <> [EndTime]");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0c85f4b-a175-441a-973e-9f66d6ed0001"),
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            EndTime = new TimeOnly(18, 30, 0),
                            GracePeriodMinutes = 15,
                            IsActive = true,
                            IsDeleted = false,
                            IsNightShift = false,
                            ShiftCode = "GENERAL",
                            ShiftName = "General Shift",
                            StartTime = new TimeOnly(9, 30, 0)
                        });
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.WorkLocations.WorkLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("AllowedRadiusMeters")
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("India");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsGeoFenceEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("BranchId", "LocationCode")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkLocations_BranchId_LocationCode");

                    b.ToTable("WorkLocations", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_WorkLocations_CoordinatePair", "([Latitude] IS NULL AND [Longitude] IS NULL) OR ([Latitude] IS NOT NULL AND [Longitude] IS NOT NULL)");

                            t.HasCheckConstraint("CK_WorkLocations_Latitude", "[Latitude] IS NULL OR [Latitude] BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_WorkLocations_LocationCode", "LTRIM(RTRIM([LocationCode])) <> ''");

                            t.HasCheckConstraint("CK_WorkLocations_LocationName", "LTRIM(RTRIM([LocationName])) <> ''");

                            t.HasCheckConstraint("CK_WorkLocations_Longitude", "[Longitude] IS NULL OR [Longitude] BETWEEN -180 AND 180");

                            t.HasCheckConstraint("CK_WorkLocations_Radius", "[AllowedRadiusMeters] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("638b4a96-b60f-4cfb-b5a8-5bf4b304896a"),
                            AllowedRadiusMeters = 100,
                            BranchId = new Guid("b3e36a15-4efb-441e-bbd8-f6cf916f6107"),
                            City = "Patna",
                            CompanyId = new Guid("ec8af472-df65-43d4-9abf-9378e553e455"),
                            Country = "India",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:seed",
                            IsActive = true,
                            IsDeleted = false,
                            IsGeoFenceEnabled = true,
                            LocationCode = "PATNA-OFFICE",
                            LocationName = "Patna Office",
                            State = "Bihar"
                        });
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Attendance.AttendanceRecord", b =>
                {
                    b.HasOne("LCAP.HRMS.Domain.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCAP.HRMS.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCAP.HRMS.Domain.Shifts.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCAP.HRMS.Domain.WorkLocations.WorkLocation", "WorkLocation")
                        .WithMany()
                        .HasForeignKey("WorkLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Employee");

                    b.Navigation("Shift");

                    b.Navigation("WorkLocation");
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Branches.Branch", b =>
                {
                    b.HasOne("LCAP.HRMS.Domain.Companies.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Departments.Department", b =>
                {
                    b.HasOne("LCAP.HRMS.Domain.Companies.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCAP.HRMS.Domain.Departments.Department", "ParentDepartment")
                        .WithMany("Children")
                        .HasForeignKey("CompanyId", "ParentDepartmentId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Designations.Designation", b =>
                {
                    b.HasOne("LCAP.HRMS.Domain.Companies.Company", "Company")
                        .WithMany("Designations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Employees.Employee", b =>
                {
                    b.HasOne("LCAP.HRMS.Domain.Branches.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCAP.HRMS.Domain.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCAP.HRMS.Domain.Departments.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCAP.HRMS.Domain.Designations.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCAP.HRMS.Domain.Employees.Employee", "ReportingManager")
                        .WithMany()
                        .HasForeignKey("ReportingManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LCAP.HRMS.Domain.Shifts.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCAP.HRMS.Domain.WorkLocations.WorkLocation", "WorkLocation")
                        .WithMany()
                        .HasForeignKey("WorkLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("Designation");

                    b.Navigation("ReportingManager");

                    b.Navigation("Shift");

                    b.Navigation("WorkLocation");
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Shifts.Shift", b =>
                {
                    b.HasOne("LCAP.HRMS.Domain.Companies.Company", "Company")
                        .WithMany("Shifts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.WorkLocations.WorkLocation", b =>
                {
                    b.HasOne("LCAP.HRMS.Domain.Branches.Branch", "Branch")
                        .WithMany("WorkLocations")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCAP.HRMS.Domain.Companies.Company", "Company")
                        .WithMany("WorkLocations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Branches.Branch", b =>
                {
                    b.Navigation("WorkLocations");
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Companies.Company", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Departments");

                    b.Navigation("Designations");

                    b.Navigation("Shifts");

                    b.Navigation("WorkLocations");
                });

            modelBuilder.Entity("LCAP.HRMS.Domain.Departments.Department", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
