import test from 'node:test';import assert from 'node:assert/strict';import {readFile,writeFile} from 'node:fs/promises';
const base='http://127.0.0.1:5095',admin=(await readFile(new URL('../../artifacts/day05/access-token.txt',import.meta.url),'utf8')).trim(),evidence=[];
async function call(method,path,body,status=200,token=admin){const r=await fetch(base+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const raw=await r.text();assert.equal(r.status,status,method+' '+path+': '+raw);evidence.push({method,path,status});return raw?JSON.parse(raw).data:undefined;}
async function token(role,companyId,employeeId){const r=await fetch(base+'/test/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role,companyId,employeeId})});assert.equal(r.status,200);return r.text();}
async function clock(day,hour=13,minute=0){const r=await fetch(base+'/test/clock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({utc:`2026-09-${String(day).padStart(2,'0')}T${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}:00Z`})});assert.equal(r.status,204);}
const masters={};for(const key of ['companies','branches','departments','designations','shifts'])masters[key]=await call('GET','/api/'+key);const companyId=masters.companies.find(c=>c.companyCode==='LCAP').id,branchId=masters.branches[0].id;
await clock(20);const loc=await call('POST','/api/work-locations',{companyId,branchId,locationCode:'TEST-DAY05-GEO',locationName:'Synthetic Day 5 Office',latitude:0,longitude:0,allowedRadiusMeters:100,isGeoFenceEnabled:true},201);
const defaults={companyId,branchId,departmentId:masters.departments[0].id,designationId:masters.designations[0].id,shiftId:masters.shifts[0].id,workLocationId:loc.id,firstName:'Synthetic',lastName:'Regularisation Tester',mobileNumber:'0000000000',dateOfJoining:'2026-01-01',employmentType:5,employeeStatus:1,isActive:true};
async function employee(code,reportingManagerId){const row=await call('POST','/api/employees',{...defaults,employeeCode:code,reportingManagerId},201);return {row,token:await token('Employee',companyId,row.id)};}
const managerA=await employee('TEST-DAY05-MANAGER-A'),managerB=await employee('TEST-DAY05-MANAGER-B'),main=await employee('TEST-DAY05-REG',managerA.row.id),managerToken=await token('Manager',companyId,managerA.row.id),otherManagerToken=await token('Manager',companyId,managerB.row.id),hr=await token('HRAdmin',companyId);
const gps={latitude:0,longitude:0,accuracyMeters:10};let rawFourth,request;
async function raw(e,day,checkout=true){await clock(day,4,20);const r=await call('POST','/api/attendance/check-in',gps,201,e.token);if(checkout){await clock(day);await call('POST','/api/attendance/check-out',gps,200,e.token);}return r;}
const body=(day,type=3)=>({attendanceDate:`2026-09-${String(day).padStart(2,'0')}`,requestType:type,requestedCheckInTime:[1,3,5,6].includes(type)?`2026-09-${String(day).padStart(2,'0')}T04:10:00Z`:null,requestedCheckOutTime:[2,4,5,6].includes(type)?`2026-09-${String(day).padStart(2,'0')}T13:01:00Z`:null,employeeReason:'Biometric/mobile clocking issue'});
const submit=(b,e=main)=>call('POST','/api/attendance-regularisations',b,201,e.token);
test('signed JWT roles, self identity, company and manager scope',async()=>{
 assert.equal((await fetch(base+'/api/health')).status,200);const spec=await(await fetch(base+'/swagger/v1/swagger.json')).json();assert.ok(spec.paths['/api/attendance-regularisations']);
 await call('GET','/api/attendance-regularisations/me',null,401,null);await call('POST','/api/attendance-regularisations',{...body(11),employeeId:managerA.row.id},400,main.token);
 for(let day=8;day<=11;day++)rawFourth=await raw(main,day);assert.equal(rawFourth.evaluation.penaltyTriggered,true);await clock(20);request=await submit(body(11));assert.equal(request.status,3);assert.equal(request.reportingManagerId,managerA.row.id);
 assert.equal((await call('GET','/api/attendance-regularisations/my-team',null,200,managerToken)).length,1);assert.equal((await call('GET','/api/attendance-regularisations/my-team',null,200,otherManagerToken)).length,0);
 await call('POST',`/api/attendance-regularisations/${request.id}/approve`,{},403,otherManagerToken);await call('POST',`/api/attendance-regularisations/${request.id}/approve`,{},403,hr);await call('GET',`/api/attendance-regularisations/me/${request.id}`,null,403,managerB.token);
});
test('realistic correction preserves raw and original evaluation while flagging penalty',async()=>{
 const r=await call('POST',`/api/attendance-regularisations/${request.id}/approve`,{reviewerRemarks:'Verified clocking issue'},200,managerToken);assert.equal(r.status,7);assert.equal(r.policyImpactReviewRequired,true);
 const effective=await call('GET','/api/attendance/effective/me?date=2026-09-11',null,200,main.token);assert.equal(effective.effectiveCheckInTime,'2026-09-11T04:10:00+00:00');assert.equal(effective.originalCheckInTime,'2026-09-11T04:20:00+00:00');assert.equal(effective.evaluation.isLate,false);assert.equal(effective.evaluation.evaluationVersion,2);
 const old=await call('GET',`/api/attendance/${rawFourth.attendanceId}/evaluation`,null,200,main.token);assert.equal(old.isLate,true);assert.equal(old.evaluationVersion,1);
 const events=await call('GET',`/api/employees/${main.row.id}/attendance-penalties`,null,200,main.token);assert.equal(events.length,1);assert.equal(events[0].status,1);assert.equal(events[0].policyImpactReviewRequired,true);
 const audit=await call('GET',`/api/attendance-regularisations/${request.id}/audit`,null,200,main.token);for(const action of ['Submitted','Approved','CorrectionApplied','EffectiveStateChanged','ReevaluationTriggered','PolicyImpactReviewRequired'])assert.ok(audit.some(a=>a.action===action));
 await call('POST',`/api/attendance-regularisations/${request.id}/approve`,{},409,managerToken);await call('POST',`/api/attendance-regularisations/${request.id}/cancel`,{cancellationReason:'Cannot withdraw'},409,main.token);
 for(const dto of [effective,r,events])for(const field of ['latitude','longitude','bankAccount','salary'])assert.ok(!JSON.stringify(dto).toLowerCase().includes('"'+field.toLowerCase()+'"'));
});
test('duplicate submission and approve versus reject serialize',async()=>{
 const b=body(12,6);const responses=await Promise.all([1,2].map(()=>fetch(base+'/api/attendance-regularisations',{method:'POST',headers:{Authorization:'Bearer '+main.token,'Content-Type':'application/json'},body:JSON.stringify(b)})));assert.deepEqual(responses.map(r=>r.status).sort(),[201,409]);const row=(await responses.find(r=>r.status===201).json()).data;
 const reviews=await Promise.all(['approve','reject'].map(action=>fetch(base+`/api/attendance-regularisations/${row.id}/${action}`,{method:'POST',headers:{Authorization:'Bearer '+managerToken,'Content-Type':'application/json'},body:JSON.stringify({reviewerRemarks:'Concurrent review test'})})));assert.deepEqual(reviews.map(r=>r.status).sort(),[200,409]);
});
test('two approvals create one correction; missing raw produces no fabricated attendance',async()=>{
 const row=await submit(body(13,6));const responses=await Promise.all([1,2].map(()=>fetch(base+`/api/attendance-regularisations/${row.id}/approve`,{method:'POST',headers:{Authorization:'Bearer '+managerToken,'Content-Type':'application/json'},body:'{}'})));assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);const effective=await call('GET','/api/attendance/effective/me?date=2026-09-13',null,200,main.token);assert.equal(effective.attendanceRecordId,null);assert.equal(effective.source,2);assert.equal(effective.evaluation.isLate,false);
});
test('missed checkout retains null raw punch and next raw check-in succeeds',async()=>{
 const r=await raw(main,14,false);await clock(20);const row=await submit(body(14,2));await call('POST',`/api/attendance-regularisations/${row.id}/approve`,{},200,managerToken);const effective=await call('GET','/api/attendance/effective/me?date=2026-09-14',null,200,main.token);assert.equal(effective.originalCheckOutTime,null);assert.ok(effective.effectiveCheckOutTime);const original=await call('GET','/api/attendance/'+r.attendanceId,null,200,main.token);assert.equal(original.checkOutTime,null);await raw(main,20,true);
});
test('rejection remarks, cancellation, invalid data, HR isolation and manager change',async()=>{
 await clock(20,14);const row=await submit(body(15,6));await call('POST',`/api/attendance-regularisations/${row.id}/reject`,{},400,managerToken);await call('POST',`/api/attendance-regularisations/${row.id}/reject`,{reviewerRemarks:'Insufficient evidence'},200,managerToken);await call('POST',`/api/attendance-regularisations/${row.id}/approve`,{},409,managerToken);
 const cancel=await submit(body(15,6));await call('POST',`/api/attendance-regularisations/${cancel.id}/cancel`,{cancellationReason:'Withdraw'},200,main.token);await call('POST',`/api/attendance-regularisations/${cancel.id}/approve`,{},409,managerToken);
 for(const b of [{...body(16,6),attendanceDate:'2027-01-01'},{...body(16,6),employeeReason:''},{...body(16,6),requestedCheckOutTime:'2026-09-16T03:00:00Z'}])await call('POST','/api/attendance-regularisations',b,400,main.token);
 const old=await submit(body(16,6));await call('PUT','/api/employees/'+main.row.id,{...defaults,employeeCode:main.row.employeeCode,reportingManagerId:managerB.row.id});await call('POST',`/api/attendance-regularisations/${old.id}/approve`,{},403,otherManagerToken);await call('POST',`/api/attendance-regularisations/${old.id}/approve`,{},200,managerToken);const next=await submit(body(17,6));assert.equal(next.reportingManagerId,managerB.row.id);
 const foreign=await token('HRAdmin','11111111-1111-1111-1111-111111111111');assert.equal((await call('GET','/api/attendance-regularisations',null,200,foreign)).length,0);await call('GET',`/api/attendance-regularisations/${old.id}`,null,403,foreign);
});
test('browser fixtures and safe request evidence',async()=>{
 const browser=await employee('TEST-DAY05-BROWSER',managerA.row.id);await raw(browser,18);await raw(browser,19);await clock(20,14);const reject=await submit(body(19),browser);
 const info={employeeId:browser.row.id,companyId,branchId,managerId:managerA.row.id,rejectRequestId:reject.id,rawFourthId:rawFourth.attendanceId,mainEmployeeId:main.row.id};
 await writeFile(new URL('../../artifacts/day05/fixture-ids.json',import.meta.url),JSON.stringify(info));for(const [file,value]of [['browser-token.txt',browser.token],['manager-token.txt',managerToken],['hr-token.txt',hr]])await writeFile(new URL('../../artifacts/day05/'+file,import.meta.url),value);await writeFile(new URL('../../artifacts/day05/http-evidence.json',import.meta.url),JSON.stringify(evidence,null,2));
});
